<a href="https://colab.research.google.com/github/Alchem1st18/Numpy_pandas_learnings/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3],dtype = 'int16')
print(a)

[1 2 3]


In [ ]:
b = np.array([[1.2,2.4,3.6],[9.8,8.7,7.6]])
print(b)


[[1.2 2.4 3.6]
 [9.8 8.7 7.6]]


In [ ]:
#getting dimensions
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
#getting shape
print(a.shape)
print(b.shape)


(3,)
(2, 3)


In [ ]:
#getting datatype
print(a.dtype)  #generally, if not specified its int64. we explicityly gave the dtpe as int16
print(b.dtype)

int16
float64


In [ ]:
#getting size
a.itemsize     #i.e. the number of bytes for each element. [dtype is int16 so 2 bytes]

2

In [ ]:
#getting total size
a.size*a.itemsize
#or
a.nbytes

6

Accessing/Changing values


In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [ ]:
a.shape

(2, 7)

In [ ]:
#accesing any index in matrix
a[1][2]

10

In [ ]:
#accessing complete row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
#accessing complete column
a[:,1]

array([2, 9])

In [ ]:
#accesing in ranges + skips in between  [start index : end index : step size]
a[0,1:5:2]

array([2, 4])

In [28]:
#changing elements
a[1][2] = 45
a[:,3] = 23
a[0,:] = 55

In [29]:
print(a)

[[55 55 55 55 55 55 55]
 [ 8  9 45 23 12 13 14]]


In [33]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [34]:
b.shape

(2, 2, 2)

In [36]:
#accessing elements [start finding from OUTSIDE-to-INSIDE]
b[0][1][1]
#or
b[0,1,1]

4

In [37]:
b[1][:][1]

array([7, 8])

In [38]:
#if we want to change/replace, ENSURE THE DIAMETERS ARE SAME
b[0][1][0] = 123 # single element so change it
b[1][:][1] = [234,345]  # a list so change it to a list with same dimensions itself

In [39]:
b

array([[[  1,   2],
        [123,   4]],

       [[  5,   6],
        [234, 345]]])

Initializing arrays

In [45]:
#create a matrix having all 0s or all 1s
np.zeros((2,3))  # inner numbers are dimensions
np.ones((3,2,1), dtype = 'int8') # data type can also be specified


array([[[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]]], dtype=int8)

In [47]:
#initialize matrix with any value other tha 0/1
np.full((2,3),56)  # first param = dimensions , second param = value
x = np.full(a.shape,345)
print(x)

[[345 345 345 345 345 345 345]
 [345 345 345 345 345 345 345]]


In [48]:
#initialize random values matrix
np.random.rand(4,2)

array([[0.4542586 , 0.6924035 ],
       [0.94243555, 0.96145307],
       [0.92359815, 0.69510258],
       [0.77040792, 0.30187879]])

In [55]:
np.random.randint(7,size=(2,3))  #first value = random b/w 0 and first param
np.random.randint(-2,6,size=(3,4)) # first 2 parameters = boundary from which rand has to be taken

array([[ 3,  5,  1,  5],
       [-2, -2,  0,  4],
       [ 4, -2,  2,  5]])

In [59]:
ar = np.array([[1,2,3]])
np.repeat(ar,3,axis = 0) #axis = 0 [means vertical] , axis = 1[means horizontal]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [77]:
temp = np.ones((5,5))
print(temp)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [79]:
mid = np.zeros((3,3))
mid[1,1] = 9;
print(mid)


[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [81]:
temp[1:-1,1:-1] = mid

In [82]:
print(temp)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Copying arrays errors

In [85]:
a = np.array([1,2,3])

b = a   #some what like pass by reference. change b and a also changes
#and
b = a.copy()  #some what like pass by value. changes in b do not affect a

# both are totally different




Mathematics


In [87]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [88]:
a-2


array([-1,  0,  1,  2,  3])

In [89]:
a*2

array([ 2,  4,  6,  8, 10])

In [94]:
b = np.array([3,4,5,6,7])
a+b      #ensure that a and b are the same SIZE
#or
a*b

array([ 3,  8, 15, 24, 35])

In [93]:
np.sin(b)
np.cos(b)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029,  0.75390225])

Linear Algebra

In [98]:
a = np.ones((4,3))
b = np.full((3,4),2)

#a*b       #this wont work as dimensions of a and b are different
######
np.matmul(a,b) #but in matrix multiplication, cols of 1st matrix must be equal to rows of 2nd matrix [here, 3==3]. so matmul is possible


array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [99]:
arr = np.identity(3)  #gives identity matrix of size 3.
np.linalg.det(arr)   #determinant of identity matrix

1.0

Statistics


In [100]:
stats = np.array([1,2,3,4,5])
np.min(stats)

1

In [101]:
np.max(stats)

5

In [105]:
multi = np.array([[1,2,3],[4,5,6]])
print(multi)
np.min(multi,axis=0)   #min value of columns

[[1 2 3]
 [4 5 6]]


array([1, 2, 3])

In [104]:
np.min(multi,axis = 1)   # min value of rows

array([1, 4])

In [107]:
np.sum(multi)
np.sum(multi,axis = 0)

array([5, 7, 9])

Reorganizing Data

In [108]:
prev = np.array([[1,2,3],[4,5,6]])
print(prev)

[[1 2 3]
 [4 5 6]]


In [114]:
curr = prev.reshape((6,1))  # reshaping array of 2*3 into 6*1
   #ensure that while reshaping total elements remain same
#u cant reshape to say 10*2 or 8*1 [cause 2*3 is 6. the multi of the new dimensions should be equal to 6]
meh = prev.reshape((2,3,1))
print(meh)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


 Stacking datatypes

In [119]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
np.vstack((x,y))
#or
np.vstack((x,y,x,y))  #just ensure sizes of both vectors are same

a = np.array([1,2])
b = np.array([1,2,3])
#np.hstack(a,b)   #throws error

In [116]:
np.hstack((x,y))

array([1, 2, 3, 4, 5, 6, 7, 8])

Miscellaneous

In [121]:
mydata = np.genfromtxt('data.txt',delimiter=',')
mydata.astype('int16')  #makes a copy, doesnt change the original data
mydata = mydata.astype('int16')  #this actually changes the datatype

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int16)

In [123]:
mydata>15

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [124]:
mydata[mydata>15]

array([16., 17., 18., 19., 20.])

In [127]:
 #we can also index a numpy array with the help of list
 aa = np.array([1,2,3,4,5,6,7,8])
 aa[[1,2,4,6]]

array([2, 3, 5, 7])

In [130]:
np.any(mydata>16,axis =1) #checks each column if any value in column value is greater than 15

array([False, False, False,  True])

In [132]:
(~(mydata>7) & (mydata<18))  # ~ symbol means not

array([[ True,  True,  True,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [137]:
mydata[[0,1,2,3],[1,2,3,4]]

array([ 2.,  8., 14., 20.])

In [153]:
mydata[[0,2,3],2:-1]

array([[ 3.,  4.],
       [13., 14.],
       [18., 19.]])